name: Deploy Lambda
on:
  push:
    branches:
      - master
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Lint and Syntax Check
        run: |
          python -m py_compile *.py
          pip install flake8
          flake8 . --exclude=venv,.venv,env,bin,lib,deps --count --statistics  --ignore=E501,E127,E128,W503,E126
      - name: Run Unit Tests
        # keep pytest out of production, only used for testing
        run: | 
          pip install pytest
          pip install -r requirements.txt
          pytest test_city_weather_data.py

      - name: Deploy to AWS
        if: success() # only if tests passed
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-north-1
          function_name: weatherAggregator
          source: .